// PDF yaratmaq üçün utility funksiya
// Tauri və web üçün uyğunlaşdırılmış təkmil hesabat sistemi

export const generateDailyReport = (locale: string = 'az', dashboardData: any = null, isDarkMode: boolean = false) => {
  const today = new Date()
  const dateStr = today.toLocaleString(locale === 'az' ? 'az-AZ' : locale === 'ru' ? 'ru-RU' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
  
  const translations = {
    az: {
      title: 'Gündəlik Hesabat',
      date: 'Hesabat Tarixi',
      summary: 'Əsas Göstəricilər',
      orders: 'Sifarişlər',
      revenue: 'Ümumi Gəlir',
      expenses: 'Xərclər',
      profit: 'Xalis Mənfəət',
      topProducts: 'Populyar Məhsullar (Top 10)',
      product: 'Məhsulun Adı',
      quantity: 'Satış Sayı',
      amount: 'Məbləğ (₼)',
      systemActivity: 'Sistem Fəaliyyəti',
      activeUsers: 'Müştəri Sayı',
      transactions: 'Tranzaksiyalar',
      avgOrderValue: 'Orta Çek',
      footer: 'Bu sənəd YessirPOS Premium sistemində rəqəmsal olaraq yaradılmışdır.',
      currency: '₼',
      headerTag: 'Rəsmi Hesabat',
      generatedAt: 'Yaradılma vaxtı'
    },
    en: {
      title: 'Daily Business Report',
      date: 'Report Date',
      summary: 'Key Performance Indicators',
      orders: 'Total Orders',
      revenue: 'Gross Revenue',
      expenses: 'Expenses',
      profit: 'Net Profit',
      topProducts: 'Top Selling Products (Top 10)',
      product: 'Product Name',
      quantity: 'Qty Sold',
      amount: 'Amount',
      systemActivity: 'System Activity Overview',
      activeUsers: 'Total Customers',
      transactions: 'Transactions',
      avgOrderValue: 'Avg. Order Value',
      footer: 'This document was digitally generated by YessirPOS Premium.',
      currency: '₼',
      headerTag: 'Official Business Report',
      generatedAt: 'Generated at'
    },
    ru: {
      title: 'Ежедневный бизнес-отчет',
      date: 'Дата отчета',
      summary: 'Ключевые показатели',
      orders: 'Всего заказов',
      revenue: 'Валовой доход',
      expenses: 'Расходы',
      profit: 'Чистая прибыль',
      topProducts: 'Топ популярных товаров (10)',
      product: 'Название товара',
      quantity: 'Продано',
      amount: 'Сумма',
      systemActivity: 'Обзор активности системы',
      activeUsers: 'Клиенты',
      transactions: 'Транзакции',
      avgOrderValue: 'Средний чек',
      footer: 'Этот документ был создан в цифровом виде в YessirPOS Premium.',
      currency: '₼',
      headerTag: 'Официальный отчет',
      generatedAt: 'Время создания'
    }
  }
  
  const t = translations[locale as keyof typeof translations] || translations.az
  
  const reportData = dashboardData ? {
    orders: dashboardData.kpis?.totalTransactions || 0,
    revenue: dashboardData.kpis?.grossRevenue || 0,
    expenses: dashboardData.kpis?.totalExpenses || 0,
    profit: dashboardData.kpis?.netRevenue || 0,
    topProducts: (dashboardData.topProducts || []).map((p: any) => ({
      name: p.name,
      quantity: p.soldQty,
      amount: p.totalRevenue
    })),
    activeUsers: dashboardData.kpis?.totalCustomers || 0,
    transactions: dashboardData.kpis?.totalTransactions || 0,
    avgOrderValue: Math.round(dashboardData.kpis?.avgOrderValue || 0)
  } : {
    orders: 0, revenue: 0, expenses: 0, profit: 0, topProducts: [], 
    activeUsers: 0, transactions: 0, avgOrderValue: 0
  }
  
  const colors = {
    primary: '#7367F0',
    primaryLight: 'rgba(115, 103, 240, 0.1)',
    bg: isDarkMode ? '#1a1a2e' : '#ffffff',
    text: isDarkMode ? '#ffffff' : '#1a1a2e',
    textMuted: isDarkMode ? '#8B8B9A' : '#64748b',
    cardBg: isDarkMode ? '#1e1e3b' : '#f8f9fc',
    border: isDarkMode ? '#2B2B45' : '#e2e8f0',
    success: '#10b981',
    danger: '#ef4444',
    warning: '#f59e0b'
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="${locale}">
    <head>
      <meta charset="UTF-8">
      <style>
        @import url('https://fonts.cdnfonts.com/css/sf-pro-display');
        
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
          font-family: 'SF Pro Display', -apple-system, sans-serif;
          padding: 40px;
          background-color: ${colors.bg};
          color: ${colors.text};
          line-height: 1.5;
        }

        .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 50px;
          border-bottom: 1px solid ${colors.border};
          padding-bottom: 30px;
        }

        .logo-section h1 {
          font-size: 28px;
          font-weight: 800;
          color: ${colors.primary};
          letter-spacing: -0.5px;
        }

        .logo-section p {
          font-size: 11px;
          text-transform: uppercase;
          font-weight: 700;
          letter-spacing: 2px;
          opacity: 0.5;
        }

        .report-info { text-align: right; }
        .report-info h2 { font-size: 20px; font-weight: 700; margin-bottom: 5px; }
        .report-info p { font-size: 13px; color: ${colors.textMuted}; }

        .kpi-grid {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 15px;
          margin-bottom: 40px;
        }

        .kpi-card {
          padding: 20px;
          border-radius: 16px;
          background: ${colors.cardBg};
          border: 1px solid ${colors.border};
        }

        .kpi-label {
          font-size: 12px;
          font-weight: 700;
          color: ${colors.textMuted};
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 10px;
        }

        .kpi-value {
          font-size: 22px;
          font-weight: 800;
          letter-spacing: -0.5px;
        }

        .section-title {
          font-size: 16px;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 1px;
          margin-bottom: 20px;
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .section-title::after {
          content: "";
          flex: 1;
          height: 1px;
          background: ${colors.border};
        }

        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 40px;
        }

        th {
          text-align: left;
          padding: 12px 15px;
          font-size: 11px;
          color: ${colors.textMuted};
          text-transform: uppercase;
          font-weight: 800;
          border-bottom: 2px solid ${colors.border};
        }

        td {
          padding: 15px;
          font-size: 13px;
          font-weight: 600;
          border-bottom: 1px solid ${colors.border};
        }

        .tr-total { background: ${colors.primaryLight}; color: ${colors.primary}; }
        
        .activity-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
        }

        .activity-card {
          padding: 15px;
          border-radius: 12px;
          border-left: 4px solid ${colors.primary};
          background: ${colors.cardBg};
        }

        .activity-card span { font-size: 11px; font-weight: 700; color: ${colors.textMuted}; display: block; margin-bottom: 5px; }
        .activity-card strong { font-size: 18px; font-weight: 800; }

        .footer {
          margin-top: 80px;
          padding-top: 20px;
          border-top: 1px solid ${colors.border};
          text-align: center;
        }

        .footer p { font-size: 12px; color: ${colors.textMuted}; font-weight: 500; }
        
        @page { size: A4; margin: 0; }
        @media print {
          body { -webkit-print-color-adjust: exact; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo-section">
          <p>${t.headerTag}</p>
          <h1>YessirPOS</h1>
        </div>
        <div class="report-info">
          <h2>${t.title}</h2>
          <p>${t.generatedAt}: ${dateStr}</p>
        </div>
      </div>

      <div class="section-title">${t.summary}</div>
      <div class="kpi-grid">
        <div class="kpi-card">
          <div class="kpi-label">${t.orders}</div>
          <div class="kpi-value" style="color: ${colors.primary}">${reportData.orders}</div>
        </div>
        <div class="kpi-card">
          <div class="kpi-label">${t.revenue}</div>
          <div class="kpi-value" style="color: ${colors.success}">${reportData.revenue.toLocaleString()} ${t.currency}</div>
        </div>
        <div class="kpi-card">
          <div class="kpi-label">${t.expenses}</div>
          <div class="kpi-value" style="color: ${colors.danger}">${reportData.expenses.toLocaleString()} ${t.currency}</div>
        </div>
        <div class="kpi-card">
          <div class="kpi-label">${t.profit}</div>
          <div class="kpi-value" style="color: ${reportData.profit >= 0 ? colors.success : colors.danger}">
            ${reportData.profit.toLocaleString()} ${t.currency}
          </div>
        </div>
      </div>

      ${reportData.topProducts.length > 0 ? `
      <div class="section-title">${t.topProducts}</div>
      <table>
        <thead>
          <tr>
            <th style="width: 50px">#</th>
            <th>${t.product}</th>
            <th style="text-align: right">${t.quantity}</th>
            <th style="text-align: right">${t.amount}</th>
          </tr>
        </thead>
        <tbody>
          ${reportData.topProducts.map((p: any, i: number) => `
            <tr>
              <td>${i + 1}</td>
              <td>${p.name}</td>
              <td style="text-align: right">${p.quantity}</td>
              <td style="text-align: right">${p.amount.toLocaleString()} ${t.currency}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      ` : ''}

      <div class="section-title">${t.systemActivity}</div>
      <div class="activity-grid">
        <div class="activity-card">
          <span>${t.activeUsers}</span>
          <strong>${reportData.activeUsers}</strong>
        </div>
        <div class="activity-card">
          <span>${t.transactions}</span>
          <strong>${reportData.transactions}</strong>
        </div>
        <div class="activity-card">
          <span>${t.avgOrderValue}</span>
          <strong>${reportData.avgOrderValue} ${t.currency}</strong>
        </div>
      </div>

      <div class="footer">
        <p>${t.footer}</p>
      </div>
    </body>
    </html>
  `
  
  // Tauri və Web uyğun çap üsulu (hidden iframe)
  const iframe = document.createElement('iframe')
  iframe.style.display = 'none'
  document.body.appendChild(iframe)
  
  if (iframe.contentWindow) {
    const doc = iframe.contentWindow.document
    doc.open()
    doc.write(htmlContent)
    doc.close()
    
    setTimeout(() => {
      iframe.contentWindow?.focus()
      iframe.contentWindow?.print()
      
      // Iframe-i təmizlə
      setTimeout(() => {
        document.body.removeChild(iframe)
      }, 1000)
    }, 500)
  }
}
