// PDF yaratmaq üçün utility funksiya
// jsPDF kitabxanası olmadan sadə HTML-to-PDF yanaşması

export const generateDailyReport = (locale: string = 'az') => {
  const today = new Date()
  const dateStr = today.toLocaleDateString(locale === 'az' ? 'az-AZ' : locale === 'ru' ? 'ru-RU' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
  
  const translations = {
    az: {
      title: 'Gündəlik Hesabat',
      date: 'Tarix',
      summary: 'Ümumi Məlumat',
      orders: 'Sifarişlər',
      revenue: 'Gəlir',
      expenses: 'Xərclər',
      profit: 'Xalis Mənfəət',
      topProducts: 'Ən Çox Satılan Məhsullar',
      product: 'Məhsul',
      quantity: 'Miqdar',
      amount: 'Məbləğ',
      systemActivity: 'Sistem Fəaliyyəti',
      activeUsers: 'Aktiv İstifadəçilər',
      transactions: 'Əməliyyatlar',
      avgOrderValue: 'Orta Sifariş Dəyəri',
      footer: 'Bu hesabat YessirPOS sistemi tərəfindən avtomatik yaradılmışdır.',
      currency: '₼'
    },
    en: {
      title: 'Daily Report',
      date: 'Date',
      summary: 'Summary',
      orders: 'Orders',
      revenue: 'Revenue',
      expenses: 'Expenses',
      profit: 'Net Profit',
      topProducts: 'Top Selling Products',
      product: 'Product',
      quantity: 'Quantity',
      amount: 'Amount',
      systemActivity: 'System Activity',
      activeUsers: 'Active Users',
      transactions: 'Transactions',
      avgOrderValue: 'Avg. Order Value',
      footer: 'This report was automatically generated by YessirPOS system.',
      currency: '₼'
    },
    ru: {
      title: 'Ежедневный отчет',
      date: 'Дата',
      summary: 'Сводка',
      orders: 'Заказы',
      revenue: 'Доход',
      expenses: 'Расходы',
      profit: 'Чистая прибыль',
      topProducts: 'Самые продаваемые товары',
      product: 'Товар',
      quantity: 'Количество',
      amount: 'Сумма',
      systemActivity: 'Активность системы',
      activeUsers: 'Активные пользователи',
      transactions: 'Транзакции',
      avgOrderValue: 'Средняя стоимость заказа',
      footer: 'Этот отчет был автоматически создан системой YessirPOS.',
      currency: '₼'
    }
  }
  
  const t = translations[locale as keyof typeof translations] || translations.az
  
  // Mock data - real data ilə əvəz edilə bilər
  const reportData = {
    orders: 156,
    revenue: 45678,
    expenses: 12345,
    profit: 33333,
    topProducts: [
      { name: 'iPhone 15 Pro', quantity: 23, amount: 28750 },
      { name: 'Samsung Galaxy S24', quantity: 18, amount: 18900 },
      { name: 'MacBook Air M2', quantity: 12, amount: 38400 },
      { name: 'AirPods Pro', quantity: 45, amount: 13500 },
      { name: 'iPad Air', quantity: 15, amount: 12000 }
    ],
    activeUsers: 8,
    transactions: 234,
    avgOrderValue: 293
  }
  
  // HTML şablonu
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        @import url('https://fonts.cdnfonts.com/css/sf-pro-display');
        
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        
        body {
          font-family: 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif;
          padding: 40px;
          background: #ffffff;
          color: #1a1a2e;
        }
        
        .header {
          text-align: center;
          margin-bottom: 40px;
          border-bottom: 3px solid #7367F0;
          padding-bottom: 20px;
        }
        
        .header h1 {
          font-size: 32px;
          font-weight: 700;
          color: #7367F0;
          margin-bottom: 10px;
        }
        
        .header .date {
          font-size: 16px;
          color: #666;
          font-weight: 500;
        }
        
        .section {
          margin-bottom: 30px;
        }
        
        .section-title {
          font-size: 20px;
          font-weight: 700;
          color: #1a1a2e;
          margin-bottom: 15px;
          padding-bottom: 8px;
          border-bottom: 2px solid #e0e0e0;
        }
        
        .stats-grid {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 20px;
          margin-bottom: 30px;
        }
        
        .stat-card {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          padding: 20px;
          border-radius: 12px;
          color: white;
          box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .stat-card.revenue {
          background: linear-gradient(135deg, #10b981 0%, #059669 100%);
        }
        
        .stat-card.expenses {
          background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
        }
        
        .stat-card.profit {
          background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
        }
        
        .stat-label {
          font-size: 13px;
          opacity: 0.9;
          margin-bottom: 8px;
          font-weight: 500;
        }
        
        .stat-value {
          font-size: 28px;
          font-weight: 700;
        }
        
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 15px;
          background: white;
          box-shadow: 0 2px 4px rgba(0,0,0,0.05);
          border-radius: 8px;
          overflow: hidden;
        }
        
        thead {
          background: #7367F0;
          color: white;
        }
        
        th {
          padding: 12px;
          text-align: left;
          font-weight: 600;
          font-size: 14px;
        }
        
        td {
          padding: 12px;
          border-bottom: 1px solid #f0f0f0;
          font-size: 14px;
        }
        
        tbody tr:hover {
          background: #f9f9f9;
        }
        
        tbody tr:last-child td {
          border-bottom: none;
        }
        
        .activity-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
          margin-top: 15px;
        }
        
        .activity-card {
          background: #f8f9fa;
          padding: 20px;
          border-radius: 10px;
          border-left: 4px solid #7367F0;
        }
        
        .activity-label {
          font-size: 13px;
          color: #666;
          margin-bottom: 8px;
          font-weight: 500;
        }
        
        .activity-value {
          font-size: 24px;
          font-weight: 700;
          color: #1a1a2e;
        }
        
        .footer {
          margin-top: 50px;
          padding-top: 20px;
          border-top: 2px solid #e0e0e0;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
        
        .logo {
          font-size: 24px;
          font-weight: 700;
          color: #7367F0;
          margin-bottom: 5px;
        }
        
        @media print {
          body {
            padding: 20px;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">YessirPOS</div>
        <h1>${t.title}</h1>
        <div class="date">${t.date}: ${dateStr}</div>
      </div>
      
      <div class="section">
        <div class="section-title">${t.summary}</div>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-label">${t.orders}</div>
            <div class="stat-value">${reportData.orders}</div>
          </div>
          <div class="stat-card revenue">
            <div class="stat-label">${t.revenue}</div>
            <div class="stat-value">${reportData.revenue.toLocaleString()} ${t.currency}</div>
          </div>
          <div class="stat-card expenses">
            <div class="stat-label">${t.expenses}</div>
            <div class="stat-value">${reportData.expenses.toLocaleString()} ${t.currency}</div>
          </div>
          <div class="stat-card profit">
            <div class="stat-label">${t.profit}</div>
            <div class="stat-value">${reportData.profit.toLocaleString()} ${t.currency}</div>
          </div>
        </div>
      </div>
      
      <div class="section">
        <div class="section-title">${t.topProducts}</div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>${t.product}</th>
              <th>${t.quantity}</th>
              <th>${t.amount}</th>
            </tr>
          </thead>
          <tbody>
            ${reportData.topProducts.map((product, index) => `
              <tr>
                <td>${index + 1}</td>
                <td>${product.name}</td>
                <td>${product.quantity}</td>
                <td>${product.amount.toLocaleString()} ${t.currency}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
      
      <div class="section">
        <div class="section-title">${t.systemActivity}</div>
        <div class="activity-grid">
          <div class="activity-card">
            <div class="activity-label">${t.activeUsers}</div>
            <div class="activity-value">${reportData.activeUsers}</div>
          </div>
          <div class="activity-card">
            <div class="activity-label">${t.transactions}</div>
            <div class="activity-value">${reportData.transactions}</div>
          </div>
          <div class="activity-card">
            <div class="activity-label">${t.avgOrderValue}</div>
            <div class="activity-value">${reportData.avgOrderValue} ${t.currency}</div>
          </div>
        </div>
      </div>
      
      <div class="footer">
        ${t.footer}
      </div>
    </body>
    </html>
  `
  
  // Yeni pəncərədə aç və print et
  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    
    // Yüklənməni gözlə və print et
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print()
      }, 250)
    }
  }
}
